version: '3.7'

services:
  mid_server_with_valt_agent:
    image: mid-vault:0.1.0
    container_name: mid_server_with_valt_agent
    environment:
      # VARIALBE FOR TESTING MODE, IF SET TO TRUE
      # MID SERVER AND VAULT AGENT WILL NOT BE STARTED
      # BUT THE CONTAINER UP
      CHECK_MODE: "TRUE"
      # VALT AGENT ENV VAR
      VAULT_AGENT_EXIT_AFTER_AUTH: "true"
      VAULT_ROLE: ""
      TARGET_FILE_NAME: ""
      VAULT_ADDR: ""
      VAULT_AGENT_TEMPLATE_FILE: "/vault-agent/secret.j2"
      # MID SERVER ENV VAR
      # Mandatory Env Var
      MID_INSTANCE_URL: "https://dev121818.service-now.com/"
      MID_INSTANCE_USERNAME: ""
      MID_INSTANCE_PASSWORD: ""
      MID_SERVER_NAME: "mid-vault"
      # Optional Env Var
      MID_PROXY_HOST: ""
      MID_PROXY_PORT: ""
      MID_PROXY_USERNAME: ""
      MID_PROXY_PASSWORD: ""
      MID_SECRETS_FILE: ""
      MID_MUTUAL_AUTH_PEM_FILE: ""
      MID_SSL_BOOTSTRAP_CERT_REVOCATION_CHECK: ""
      MID_SSL_USE_INSTANCE_SECURITY_POLICY: ""

  db:
    image: "hashicorpdemoapp/product-api-db:v4280cf7"
    ports:
      - "15432:5432"
    environment:
      POSTGRES_DB: 'products'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password'

  db2:
    image: "hashicorpdemoapp/product-api-db:v4280cf7"
    ports:
      - "25432:5432"
    environment:
      POSTGRES_DB: 'products'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password2'

  db3:
    image: "hashicorpdemoapp/product-api-db:v4280cf7"
    ports:
      - "35432:5432"
    environment:
      POSTGRES_DB: 'products'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'password3'

  vault_server:
    image: hashicorp/vault:1.14.2
    container_name: vault_server
    restart: always
    ports:
      - "8200:8200"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID= 'root'
      - VAULT_DEV_LISTEN_ADDRESS= '0.0.0.0:8200'
    cap_add:
      - IPC_LOCK
    volumes:
      - ./volumes/vault/data:/vault/data
      - ./volumes/vault/config:/vault/config
      - ./volumes/vault/logs:/vault/logs
